services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "4000:4000"
    depends_on:
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - MONGO_URL=mongodb://ggaurav:gaurav264@ac-ueiynge-shard-00-00.syslkgx.mongodb.net:27017,ac-ueiynge-shard-00-01.syslkgx.mongodb.net:27017,ac-ueiynge-shard-00-02.syslkgx.mongodb.net:27017/EVNTIFY?ssl=true&replicaSet=atlas-y8jd2g-shard-0&authSource=admin&appName=Cluster0
      - REDIS_URL=redis://redis:6379
      - TMDB_API_KEY=4272ee0d1ad3ef0d74eaa1e2f6b30794

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: npm run dev -- --host 0.0.0.0 --port 5173

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"